bq_schema = [
    {"name": "Id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "IsActive", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "Number", "type": "STRING", "mode": "NULLABLE"},
    {"name": "Name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "NameEnglish", "type": "STRING", "mode": "NULLABLE"},
    {"name": "NetPrice", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "NetPriceWithDiscount", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "GrossPrice", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "CodingId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CodingName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "UnitId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "UnitName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "UnitAbbreviation", "type": "STRING", "mode": "NULLABLE"},
    {"name": "StockBalance", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "StockBalanceManuallyChangedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "StockBalanceReserved", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "StockBalanceAvailable", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "CreatedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "ChangedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "HouseWorkType", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "PurchasePrice", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "PurchasePriceManuallyChangedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "SendToWebshop", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "UsesMoss", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "ArticleLabels", "type": "RECORD", "mode": "REPEATED", "fields": [
        {"name": "Id", "type": "STRING", "mode": "NULLABLE"},
        {"name": "Name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "Description", "type": "STRING", "mode": "NULLABLE"}
    ]},
    {"name": "MessageThreads", "type": "STRING", "mode": "REPEATED"},
    {"name": "Notes", "type": "STRING", "mode": "REPEATED"},
    {"name": "IsStock", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "ShowStockInformation", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "IsServiceArticle", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "StockLocationReference", "type": "STRING", "mode": "NULLABLE"},
    {"name": "FreightCosts", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "FreightCostsManuallyChangedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "UpdateStockPrices", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "Barcodes", "type": "RECORD", "mode": "REPEATED", "fields": [
        {"name": "Barcode", "type": "STRING", "mode": "NULLABLE"},
        {"name": "BarcodeType", "type": "NUMERIC", "mode": "NULLABLE"}
    ]},
    {"name": "StockValue", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "GreenTechnologyType", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "DiscountPercentage", "type": "NUMERIC", "mode": "NULLABLE"}
]
