bq_schema = [
    {"name": "Id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "EuThirdParty", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "IsCreditInvoice", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "CurrencyCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CurrencyRate", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "CreatedByUserId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "TotalAmount", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "TotalVatAmount", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "TotalRoundings", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "TotalAmountInvoiceCurrency", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "TotalVatAmountInvoiceCurrency", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "SetOffAmountInvoiceCurrency", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "CustomerId", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "Rows",
        "type": "RECORD",
        "mode": "REPEATED",
        "fields": [
            {"name": "Id", "type": "STRING", "mode": "NULLABLE"},
            {"name": "ArticleNumber", "type": "STRING", "mode": "NULLABLE"},
            {"name": "ArticleId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "IsServiceArticle", "type": "BOOLEAN", "mode": "NULLABLE"},
            {"name": "AmountNoVat", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "PercentVat", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "LineNumber", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "IsTextRow", "type": "BOOLEAN", "mode": "NULLABLE"},
            {"name": "Text", "type": "STRING", "mode": "NULLABLE"},
            {"name": "UnitPrice", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "UnitAbbreviation", "type": "STRING", "mode": "NULLABLE"},
            {"name": "UnitAbbreviationEnglish", "type": "STRING", "mode": "NULLABLE"},
            {"name": "DiscountPercentage", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "Quantity", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "IsWorkCost", "type": "BOOLEAN", "mode": "NULLABLE"},
            {"name": "IsVatFree", "type": "BOOLEAN", "mode": "NULLABLE"},
            {"name": "CostCenterItemId1", "type": "STRING", "mode": "NULLABLE"},
            {"name": "CostCenterItemId2", "type": "STRING", "mode": "NULLABLE"},
            {"name": "CostCenterItemId3", "type": "STRING", "mode": "NULLABLE"},
            {"name": "UnitId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "ProjectId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "WorkCostType", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "WorkHours", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "MaterialCosts", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "GreenTechnologyType", "type": "NUMERIC", "mode": "NULLABLE"},
            {
                "name": "ContributionMargin",
                "type": "RECORD",
                "mode": "NULLABLE",
                "fields": [
                    {"name": "Amount", "type": "NUMERIC", "mode": "NULLABLE"},
                    {"name": "Percentage", "type": "NUMERIC", "mode": "NULLABLE"}
                ]
            }
        ]
    },
    {
        "name": "VatSpecification",
        "type": "RECORD",
        "mode": "REPEATED",
        "fields": [
            {"name": "AmountInvoiceCurrency", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "VatAmountInvoiceCurrency", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "VatPercent", "type": "NUMERIC", "mode": "NULLABLE"}
        ]
    },
    {"name": "InvoiceDate", "type": "DATE", "mode": "NULLABLE"},
    {"name": "DueDate", "type": "DATE", "mode": "NULLABLE"},
    {"name": "DeliveryDate", "type": "DATE", "mode": "NULLABLE"},
    {"name": "RotReducedInvoicingType", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "RotReducedInvoicingAmount", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "RotReducedInvoicingPercent", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "RotReducedInvoicingPropertyName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "RotReducedInvoicingOrgNumber", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "Persons",
        "type": "RECORD",
        "mode": "REPEATED",
        "fields": [
            {"name": "Ssn", "type": "STRING", "mode": "NULLABLE"},
            {"name": "Amount", "type": "NUMERIC", "mode": "NULLABLE"}
        ]
    },
    {"name": "RotReducedInvoicingAutomaticDistribution", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "ElectronicReference", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ElectronicAddress", "type": "STRING", "mode": "NULLABLE"},
    {"name": "EdiServiceDelivererId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "OurReference", "type": "STRING", "mode": "NULLABLE"},
    {"name": "YourReference", "type": "STRING", "mode": "NULLABLE"},
    {"name": "BuyersOrderReference", "type": "STRING", "mode": "NULLABLE"},
    {"name": "InvoiceCustomerName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "InvoiceAddress1", "type": "STRING", "mode": "NULLABLE"},
    {"name": "InvoiceAddress2", "type": "STRING", "mode": "NULLABLE"},
    {"name": "InvoicePostalCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "InvoiceCity", "type": "STRING", "mode": "NULLABLE"},
    {"name": "InvoiceCountryCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryCustomerName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryAddress1", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryAddress2", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryPostalCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryCity", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryCountryCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryMethodName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryTermName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryMethodCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "DeliveryTermCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CustomerIsPrivatePerson", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "TermsOfPaymentId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CustomerEmail", "type": "STRING", "mode": "NULLABLE"},
    {"name": "InvoiceNumber", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "CustomerNumber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CustomerName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "PaymentReferenceNumber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "RotPropertyType", "type": "NUMERIC", "mode": "NULLABLE"},
    {
        "name": "SalesDocumentAttachments",
        "type": "STRING",
        "mode": "REPEATED",
        "fields": [{"name": "SalesDocumentAttachment", "type": "STRING", "mode": "NULLABLE"}]
    },
    {
        "name": "MessageThreads",
        "type": "STRING",
        "mode": "REPEATED",
        "fields": [{"name": "MessageThread", "type": "STRING", "mode": "NULLABLE"}]
    },
    {
        "name": "Notes",
        "type": "STRING",
        "mode": "REPEATED",
        "fields": [{"name": "Note", "type": "STRING", "mode": "NULLABLE"}]
    },
    {"name": "HasAutoInvoiceError", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "IsNotDelivered", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "ReverseChargeOnConstructionServices", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "WorkHouseOtherCosts", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "RemainingAmount", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "RemainingAmountInvoiceCurrency", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "ReferringInvoiceId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CreatedFromOrderId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CreatedFromDraftId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "VoucherNumber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "VoucherId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CreatedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "ModifiedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "ReversedConstructionVatInvoicing", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "IncludesVat", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "SendType", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "PaymentReminderIssued", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "UsesGreenTechnology", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "IsSold", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "FactoringInvoiceStatus", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "PaymentDate", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "PaymentStatus", "type": "INTEGER", "mode": "NULLABLE"},
    {
        "name": "CreditedBy",
        "type": "RECORD",
        "mode": "REPEATED",
        "fields": [{"name": "CreditInvoiceId", "type": "STRING", "mode": "NULLABLE"}]
    },
    {
        "name": "ContributionMargin",
        "type": "RECORD",
        "mode": "NULLABLE",
        "fields": [
            {"name": "Amount", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "Percentage", "type": "NUMERIC", "mode": "NULLABLE"}
        ]
    },
    {"name": "IsDirectDebit", "type": "BOOLEAN", "mode": "NULLABLE"}
]
