bq_schema = [
    {"name": "Id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "SupplierId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "BankAccountId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "InvoiceDate", "type": "DATE", "mode": "NULLABLE"},
    {"name": "PaymentDate", "type": "DATE", "mode": "NULLABLE"},
    {"name": "DueDate", "type": "DATE", "mode": "NULLABLE"},
    {"name": "InvoiceNumber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "TotalAmount", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "Vat", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "VatHigh", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "VatMedium", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "VatLow", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "IsCreditInvoice", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "CurrencyCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CurrencyRate", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "OcrNumber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "Message", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CreatedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "ModifiedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "PlusGiroNumber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "BankGiroNumber", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "Rows",
        "type": "RECORD",
        "mode": "REPEATED",
        "fields": [
            {"name": "Id", "type": "STRING", "mode": "NULLABLE"},
            {"name": "AccountNumber", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "AccountName", "type": "STRING", "mode": "NULLABLE"},
            {"name": "VatCodeId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "VatAmount", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "ProportionalVatRateValue", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "CostCenterItemId1", "type": "STRING", "mode": "NULLABLE"},
            {"name": "CostCenterItemId2", "type": "STRING", "mode": "NULLABLE"},
            {"name": "CostCenterItemId3", "type": "STRING", "mode": "NULLABLE"},
            {"name": "Quantity", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "Weight", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "DeliveryDate", "type": "TIMESTAMP", "mode": "NULLABLE"},
            {"name": "HarvestYear", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "DebetAmount", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "CreditAmount", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "LineNumber", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "ProjectId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "TransactionText", "type": "STRING", "mode": "NULLABLE"}
        ]
    },
    {"name": "SupplierName", "type": "STRING", "mode": "NULLABLE"},
    {"name": "SupplierNumber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "IsQuickInvoice", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "IsDomestic", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "RemainingAmount", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "RemainingAmountInvoiceCurrency", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "Number", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "NumberSeries", "type": "STRING", "mode": "NULLABLE"},
    {"name": "VoucherNumber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "VoucherId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "CreatedFromDraftId", "type": "STRING", "mode": "NULLABLE"},
    {"name": "SelfEmployedWithoutFixedAddress", "type": "BOOLEAN", "mode": "NULLABLE"},
    {
        "name": "AllocationPeriods",
        "type": "RECORD",
        "mode": "REPEATED",
        "fields": [
            {"name": "Id", "type": "STRING", "mode": "NULLABLE"},
            {"name": "SupplierInvoiceDraftId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "SupplierInvoiceDraftRow", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "SupplierInvoiceId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "SupplierInvoiceRow", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "ManualVoucherId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "ManualVoucherRow", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "CustomerInvoiceId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "CustomerInvoiceRow", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "VoucherFiscalYearId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "AllocationPeriodSourceType", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "Status", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "CostCenterItemId1", "type": "STRING", "mode": "NULLABLE"},
            {"name": "CostCenterItemId2", "type": "STRING", "mode": "NULLABLE"},
            {"name": "CostCenterItemId3", "type": "STRING", "mode": "NULLABLE"},
            {"name": "ProjectId", "type": "STRING", "mode": "NULLABLE"},
            {"name": "BookkeepingDate", "type": "TIMESTAMP", "mode": "NULLABLE"},
            {"name": "CreatedUtc", "type": "TIMESTAMP", "mode": "NULLABLE"},
            {
                "name": "Rows",
                "type": "RECORD",
                "mode": "REPEATED",
                "fields": [
                    {"name": "Id", "type": "STRING", "mode": "NULLABLE"},
                    {"name": "AllocationPeriodId", "type": "STRING", "mode": "NULLABLE"},
                    {"name": "AccountNumber", "type": "NUMERIC", "mode": "NULLABLE"},
                    {"name": "Amount", "type": "NUMERIC", "mode": "NULLABLE"},
                    {"name": "Quantity", "type": "NUMERIC", "mode": "NULLABLE"},
                    {"name": "Weight", "type": "NUMERIC", "mode": "NULLABLE"},
                    {"name": "DebitCredit", "type": "NUMERIC", "mode": "NULLABLE"}
                ]
            },
            {"name": "DebitAccountNumber", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "CreditAccountNumber", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "Amount", "type": "NUMERIC", "mode": "NULLABLE"},
            {"name": "IsCredit", "type": "BOOLEAN", "mode": "NULLABLE"}
        ]
    },
    {"name": "AutoCreditDebitPairing", "type": "BOOLEAN", "mode": "NULLABLE"},
    {
        "name": "Attachments",
        "type": "STRING",
        "mode": "REPEATED"
    },
    {"name": "SetOffAmountInvoiceCurrency", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "Status", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "PaymentStatus", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "PaymentFileStatus", "type": "NUMERIC", "mode": "NULLABLE"},
    {"name": "SkipSendToBank", "type": "BOOLEAN", "mode": "NULLABLE"}
]
